schemes:
  - http
swagger: "2.0"
info:
  title: Mock Merit API
  version: 0.0.1
host: localhost:3000
basePath: /
paths:
  /templates:
    get:
      consumes:
        - application/json
      produces:
        - application/json
      summary: Get a list of templates.
      operationId: getTemplates
      responses:
        "200":
          description: Retrieved all templates.
          schema:
            type: array
            items:
              $ref: "#/definitions/Template"
  /templates/{templateId}/merits:
    get:
      consumes:
        - application/json
      produces:
        - application/json
      summary: Get a list of merits for the given template.
      operationId: getTemplatesMerits
      parameters:
        - name: templateId
          minimum: 1
          type: integer
          in: path
          required: true
        - name: userId
          minimum: 1
          type: integer
          in: query
      responses:
        "200":
          description: Retrieved all merits for the given template.
          schema:
            type: array
            items:
              $ref: "#/definitions/Merit"
  /users/{userId}/merits:
    get:
      consumes:
        - application/json
      produces:
        - application/json
      summary: Get a list of merits for the given user.
      operationId: getUsersMerits
      parameters:
        - name: templateId
          minimum: 1
          type: integer
          in: query
        - name: userId
          minimum: 1
          type: integer
          in: path
          required: true
      responses:
        "200":
          description: Retrieved all merits for the given user.
          schema:
            type: array
            items:
              $ref: "#/definitions/Merit"
    post:
      consumes:
        - application/json
      produces:
        - application/json
      summary: Create a merit for the given user.
      operationId: createUserMerit
      parameters:
        - name: merit
          in: body
          required: true
          schema:
            $ref: "#/definitions/Merit"
        - name: userId
          minimum: 1
          type: integer
          in: path
          required: true
      responses:
        "201":
          description: Created the Merit for the given user.
          schema:
            $ref: "#/definitions/Merit"
definitions:
  Merit:
    type: object
    required:
      - templateId
      - userId
    properties:
      id:
        type: integer
      templateId:
        type: integer
      userId:
        type: integer
  Template:
    type: object
    required:
      - id
      - string
    properties:
      id:
        type: integer
      name:
        type: string
