schemes:
  - http
swagger: "2.0"
info:
  title: Mock Merit API
  version: 0.0.1
host: localhost:3000
basePath: /
paths:
  /users/{userID}/merits:
    get:
      consumes:
        - application/json
      produces:
        - application/json
      summary: Get a list of merits for the given user.
      operationId: getUsersMerits
      parameters:
        - name: userID
          minimum: 1
          type: integer
          in: path
          required: true
        - name: meritTemplateID
          minimum: 1
          type: integer
          in: query
      responses:
        "200":
          description: Retrieved all merits for the given user.
          schema:
            type: array
            items:
              $ref: '#/definitions/Merit'
    post:
      consumes:
        - application/json
      produces:
        - application/json
      summary: Create a merit for the given user.
      operationId: createUserMerit
      parameters:
        - name: userID
          minimum: 1
          type: integer
          in: path
          required: true
        - name: merit
          in: body
          required: true
          schema:
            $ref: "#/definitions/Merit"
      responses:
        "201":
          description: Created the Merit for the given user.
          schema:
            $ref: '#/definitions/Merit'
definitions:
  Merit:
    type: object
    required:
      - meritTemplateId
      - userId
    properties:
      id:
        type: integer
      meritTemplateId:
        type: integer
      userId:
        type: integer
